<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><!-- HTML generated by Network Solutions Website Builder --><html xmlns="http://www.w3.org/1999/xhtml"><head><title>yousee, United Care Development Services Hyderabad, ANDHRA PRADESH test</title><meta name="robots" content="index, follow" /><meta name="description" content="UC brings a postpaid model of funding outcomes in social sectors like Education, Health and Energy &amp;amp; Environmental Services"><meta name="keywords" content="yousee Hyderabad ANDHRA PRADESH, post paid Hyderabad ANDHRA PRADESH, result based finance Hyderabad ANDHRA PRADESH, development funding Hyderabad ANDHRA PRADESH, social outcomes Hyderabad ANDHRA PRADESH, education Hyderabad ANDHRA PRADESH"><meta http-equiv="cache-control" content="no-cache"/><meta http-equiv="pragma" content="no-cache"/><meta http-equiv="expires" content="-1"/><script type="text/javascript" src="/scripts/user.js"></script><script type="text/javascript" src="/scripts/jquery.js"></script><script type="text/javascript" src="/scripts/simplegallery.js"></script><script type="text/javascript" src="/scripts/photo_album.js"></script><link rel="stylesheet" media="screen" href="/scripts/template.css" id="wb-template.css" /><link rel="stylesheet" media="all" href="/scripts/layout3.css" id="wb-layout3.css" /><link rel="stylesheet" media="all" href="/scripts/website.css" id="wb-website.css" /><link rel="stylesheet" media="print" href="/scripts/print.css" id="wb-print.css" /><link rel="stylesheet" media="all" href="/scripts/41custom.css" id="wb-custom.css" /><link rel="stylesheet" media="all" href="/scripts/icwebsiteelement.css" id="wb-icwebsiteelement.css" /></head><body onload="initClientMenu();sizeColumns();"><!-- Start content section --><div id="wb-container-outer">
<div id="wb-container-inner">
<div id="wb-layout">
<div id="wb-layout-inner">
<div id="wb-layout-top-header">
<div id="wb-navigation-subtop-header">
                        
                    </div>
<div id="wb-top-subbasenav"></div>
</div>
<div id="wb-header-nav">
<div id="wb-navigation-top-header">
<div id="wb-navigation-bottom-header">
							 
						</div>
</div>
</div>
<div id="wb-layout-header">
<div id="wb-layout-header-mask" class="wb_region">
         
<table id="wb_con__42340" class="wb_con" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td id="wb_col__45678" class="wb_col" width="50%" valign="top" style="">
<table id="dz-tablewb_element_image__1267510379275_14" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_image__1267510379275_14" class="ic-element wb-text-content"><table summary="image table" cellpadding="0" cellspacing="0" border="0" width="100%" style=""><tr>
<td align="left" valign="top">
<table cellpadding="0" cellspacing="0" border="0">
<tr>
<td align="left"><img width="125" src="../images/125_UC_Logo-3.jpg" alt="" style="" border="0" height="95"></td>
</tr>
<tr>
<td align="center" class="wb-text-content"></td>
</tr>
</table>
</td>
</tr></table></div>
</td>
</tr>
</table>
</td><td id="wb_col__5673453" class="wb_col" width="50%" valign="top" style=""></td>
</tr>
</table>
          
</div>
</div>
<div id="wb-layout-header-base"></div>
<div id="wb-layout-top-2">
<div id="wb-navigation-subtop">
                        <div><a href="../home.html" class="tertiary" target="_self"><h3>Home</h3></a></div>
<div><a href="../aboutuc.html" class="tertiary" target="_self"><h3>About UC</h3></a><div class="submenu"><div><a href="../aboutuc/ucmodel.html" class="tertiary" target="_self"><h3>UC Model</h3></a></div><div><a href="../aboutuc/team.html" class="tertiary" target="_self"><h3>Team</h3></a></div><div><a href="../aboutuc/jointheteam.html" class="tertiary" target="_self"><h3>Join the Team</h3></a></div><div><a href="../aboutuc/services.html" class="tertiary" target="_self"><h3>Services</h3></a></div><div><a href="../aboutuc/faq.html" class="tertiary" target="_self"><h3>FAQ</h3></a></div></div></div>
<div><a href="../projectspartners.html" class="tertiary" target="_self"><h3>Projects & Partners</h3></a><div class="submenu"><div><a href="../projectspartners/health.html" class="tertiary" target="_self"><h3>Health</h3></a></div><div><a href="../projectspartners/integratedprojectindore.html" class="tertiary" target="_self"><h3>Integrated Project-Indore</h3></a></div></div></div>
<div><a href="../uccertificates.html" class="tertiary" target="_self"><h3>UC Certificates</h3></a><div class="submenu"><div><a href="../uccertificates/uccertificatesacquired.html" class="tertiary" target="_self"><h3>UC Certificates-Acquired</h3></a></div><div><a href="../uccertificates/ucdocuments.html" class="tertiary" target="_self"><h3>UC Documents</h3></a></div></div></div>
<div><a href="../participate.php" class="tertiary" target="_self"><h3>Participate</h3></a></div>
<div><a href="../resources.html" class="tertiary" target="_self"><h3>Resources</h3></a><div class="submenu"><div><a href="../resources/test.php" class="tertiary" target="_self"><h3>test</h3></a></div></div></div>
<div><a href="../contactuc.html" class="tertiary" target="_self"><h3>Contact UC</h3></a></div>
<div><a href="../donateyourwaste.html" class="tertiary" target="_self"><h3>Donate Your Waste</h3></a><div class="submenu"><div><a href="../donateyourwaste/wheretodonate.html" class="tertiary" target="_self"><h3>Where to Donate</h3></a></div><div><a href="../donateyourwaste/donationsreceived.html" class="tertiary" target="_self"><h3>Donations Received</h3></a></div><div><a href="../donateyourwaste/whoaredonating.html" class="tertiary" target="_self"><h3>Who are donating</h3></a></div></div></div>

                    </div>
<div id="wb-top-subbasenav"></div>
</div>
<div id="wb-container-contentwrapper">
<div id="wb-layout-sidebar">
<div id="wb-navigation">
<div id="wb-navigation-top">
<div id="wb-navigation-bottom">
                                    <div><a href="../home.html" class="tertiary" target="_self"><h3>Home</h3></a></div>
<div><a href="../aboutuc.html" class="tertiary" target="_self"><h3>About UC</h3></a><div class="submenu"><div><a href="../aboutuc/ucmodel.html" class="tertiary" target="_self"><h3>UC Model</h3></a></div><div><a href="../aboutuc/team.html" class="tertiary" target="_self"><h3>Team</h3></a></div><div><a href="../aboutuc/jointheteam.html" class="tertiary" target="_self"><h3>Join the Team</h3></a></div><div><a href="../aboutuc/services.html" class="tertiary" target="_self"><h3>Services</h3></a></div><div><a href="../aboutuc/faq.html" class="tertiary" target="_self"><h3>FAQ</h3></a></div></div></div>
<div><a href="../projectspartners.html" class="tertiary" target="_self"><h3>Projects & Partners</h3></a><div class="submenu"><div><a href="../projectspartners/health.html" class="tertiary" target="_self"><h3>Health</h3></a></div><div><a href="../projectspartners/integratedprojectindore.html" class="tertiary" target="_self"><h3>Integrated Project-Indore</h3></a></div></div></div>
<div><a href="../uccertificates.html" class="tertiary" target="_self"><h3>UC Certificates</h3></a><div class="submenu"><div><a href="../uccertificates/uccertificatesacquired.html" class="tertiary" target="_self"><h3>UC Certificates-Acquired</h3></a></div><div><a href="../uccertificates/ucdocuments.html" class="tertiary" target="_self"><h3>UC Documents</h3></a></div></div></div>
<div><a href="../participate.php" class="tertiary" target="_self"><h3>Participate</h3></a></div>
<div><a href="../resources.html" class="tertiary" target="_self"><h3>Resources</h3></a><div class="submenu"><div><a href="../resources/test.php" class="tertiary" target="_self"><h3>test</h3></a></div></div></div>
<div><a href="../contactuc.html" class="tertiary" target="_self"><h3>Contact UC</h3></a></div>
<div><a href="../donateyourwaste.html" class="tertiary" target="_self"><h3>Donate Your Waste</h3></a><div class="submenu"><div><a href="../donateyourwaste/wheretodonate.html" class="tertiary" target="_self"><h3>Where to Donate</h3></a></div><div><a href="../donateyourwaste/donationsreceived.html" class="tertiary" target="_self"><h3>Donations Received</h3></a></div><div><a href="../donateyourwaste/whoaredonating.html" class="tertiary" target="_self"><h3>Who are donating</h3></a></div></div></div>

                                </div>
</div>
</div>
<div id="wb-basenav"></div>
<div id="wb-navbasewrap" class="wb_region">
<div class="wb_dropzone_y">&nbsp;</div>
          
</div>
</div>
<div id="wb-layout-main">
<div id="wb-layout-main-inner-1">
<div id="wb-layout-main-inner-2" class="wb_region">
            
<table id="wb_cl__912343469" cellpadding="0" cellspacing="0" class="" width="100%">
<tr>
<td>
                
<table id="wb_con__912311135646789" class="wb_con" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td id="wb_col__933222569" class="wb_col" width="100%" valign="top" style="">
                        
                    
<table id="dz-tablewb_element_php__1298662810945_30" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_php__1298662810945_30" class="ic-element wb-text-content"><html><body>

<h4>See list of Volunteering Opportunities. Sort by:</h4>

<form method="post" action="<?php echo $PHP_SELF;?>">
<input type="radio" name="item" value="Area" /> Area
<input type="radio" name="item" value="Vertical" /> Vertical
<input type="radio" name="item" value="Location" /> Location<br />
<input type="submit" />
</form>

<?php
$item = $_POST['item'];
echo "You have sorted by". " " . $item . ".<br />";

$con = mysql_connect("205.178.146.87","youseedb1","volunteeR1");
if (!$con)
  {
  die('Could not connect: ' . mysql_error());
  }

mysql_select_db("ucactivity", $con);

$result = mysql_query("SELECT *  FROM ucactivity.activity WHERE activity_by='All' ORDER BY $item");

echo "<table border='1'>
<tr>
<th>Area</th>
<th>Vertical</th>
<th>Location</th>
<th>Activity</th>
</tr>";

while($row = mysql_fetch_array($result))
  {
  echo "<tr>";
  echo "<td>" . $row['area'] . "</td>";
  echo "<td>" . $row['vertical'] . "</td>";
  echo "<td>" . $row['location'] . "</td>";
  echo "<td>" . $row['activity'] . "</td>";
  echo "</tr>";
  }
echo "</table>";

mysql_close($con);

?>

</body></html></div>
</td>
</tr>
</table>
<table id="dz-tablewb_element_html__1299002469532_8" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_html__1299002469532_8" class="ic-element wb-text-content">
<div class="wb-text-content"><TABLE border=1>
<TBODY>
<TR>
<TD>
<P><B>S NO</B></P></TD>
<TD><B>Project</B></TD>
<TD>
<P><B><FONT color=#6666ff>PostPaid</FONT></B>/ <B><FONT color=#ff3300>Available</FONT></B> </P>
<P><B>Status in INR</B> </P></TD>
<TD>
<P><B><FONT color=#6666ff>PostPaid</FONT>+</B> </P>
<P><B><FONT color=#ff3300>Available</FONT>= </B></P>
<P><B>Total Cost (INR)</B> </P></TD>
<TD>
<P><B>Certificate</B> </P>
<P><B>Document</B> </P></TD></TR>
<TR>
<TD>
<P>1</P></TD>
<TD>3,904 OutPatients attended by <B>Mobile Health Clinic</B> run by Isha Outreach for the poor in the slums of Chennai during <B>November &amp; December 2010</B> </TD>
<TD>
<SCRIPT src="https&#8203;://spreads&#8203;heets.goog&#8203;le.com/gpu&#8203;b?url=http&#8203;%3A%2F%2F1&#8203;825mpl2tu3&#8203;t0ad0qe4r9&#8203;04ad502of0&#8203;q-ss-opens&#8203;ocial.goog&#8203;leusercont&#8203;ent.com%2F&#8203;gadgets%2F&#8203;ifr%3Fup_t&#8203;itle%3DMob&#8203;ile%2520Cl&#8203;inic%2520N&#8203;ov-Dec%252&#8203;02010%26up&#8203;_chartTitl&#8203;e%26up_lab&#8203;elx%26up_l&#8203;abely%26up&#8203;_legend%3D&#8203;4%26up_3d%&#8203;3D0%26up_s&#8203;tacked%3D1&#8203;%26up_min%&#8203;3D0%26up_m&#8203;ax%26up__t&#8203;able_query&#8203;_url%3Dhtt&#8203;ps%253A%25&#8203;2F%252Fspr&#8203;eadsheets.&#8203;google.com&#8203;%252Ftq%25&#8203;3Frange%25&#8203;3DG4%25253&#8203;AH4%2526ke&#8203;y%253D0Avm&#8203;kTr7hBJRfd&#8203;ENqMGpMd00&#8203;4eHB6ODhXU&#8203;ElMSEV0S2c&#8203;%2526gid%2&#8203;53D3%2526p&#8203;ub%253D1%2&#8203;6url%3Dhtt&#8203;p%253A%252&#8203;F%252Fwww.&#8203;google.com&#8203;%252Fig%25&#8203;2Fmodules%&#8203;252Fbar-ch&#8203;art.xml%26&#8203;spreadshee&#8203;ts%3Dsprea&#8203;dsheets&amp;height=5&amp;width=25"></&#8203;script></td>
 
 <td><p><font color="6666FF">0(00.00%)</font></p><p><font color="FF3300">105,005(100.00%)</font></p><p>105,005</p></td>  
 
 <td><a href="http://www.yousee.in/images/UC-RC-Isha_Outreach_Nov-Dec_2010.pdf"><img border="0" src="http://www.yousee.in/images/113_UC_Logo-3.jpg" width="50" height="41"</a></td>
 </tr>
</table>
 
</body>
</html></SCRIPT>
</TR></TBODY></TABLE></div>
</div>
</td>
</tr>
</table>
<table id="dz-tablewb_element_docs__1298916332437_97" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="center">
<div id="wb_element_docs__1298916332437_97" class="ic-element wb-text-content">
<a target="_blank" href="../images/UC-RC-Isha_Outreach_Nov-Dec_2010.pdf"><img src="../images/doc_pdf.gif" width="50" height="50" border="0" alt="Document"></a>
<br>
<a target="_blank" href="../images/UC-RC-Isha_Outreach_Nov-Dec_2010.pdf">Nov-Dec document Mobile Clinic Project</a>
</div>
</td>
</tr>
</table>
</td>
</tr>
</table>
                
<table id="wb_con__9123444646789" class="wb_con" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td id="wb_col__933543569" class="wb_col" width="50%" valign="top" style="">
                        
<table id="dz-tablewb_element_text__9451236339" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__9451236339" class="ic-element wb-text-content">
                            
<div class="wb-text-content"></div>
                        
</div>
</td>
</tr>
</table>
                    
</td><td id="wb_col__93355554569" class="wb_col" width="50%" valign="top" style="">
                        
<table id="dz-tablewb_element_text__9451236340" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__9451236340" class="ic-element wb-text-content">
                            
<div class="wb-text-content"></div>
                        
</div>
</td>
</tr>
</table>
                    
</td>
</tr>
</table>
                
<table id="wb_con__912318765646789" class="wb_con" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td id="wb_col__933598769" class="wb_col" width="100%" valign="top" style="">
                        
<table id="dz-tablewb_element_text__9453576119" class="dz-table" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td align="left">
<div id="wb_element_text__9453576119" class="ic-element wb-text-content">
                            
<div class="wb-text-content"></div>
                        
</div>
</td>
</tr>
</table>
                    
</td>
</tr>
</table>
            
</td>
</tr>
</table>
        
</div>
</div>
</div>
<div style="clear: both"></div>
</div>
<div id="wb-layout-footer">
<div id="wb-layout-footer-inner-1" class="wb_region">
<div class="wb_dropzone_y">&nbsp;</div>
</div>
</div>
</div>
</div>
</div>
</div><table border="0" width="100%" cellpadding="0" cellspacing="0" id="other_footer">
<tr>
<td align="left" valign="middle"><p style="font-size: 10px; font-style: normal; font-family: arial,verdana,sans-serif;  font-style: normal;"><a style="text-decoration: none; font-size: 10px; font-style: normal; font-family: arial,verdana,sans-serif;  font-style: normal;" title="Web hosting" href="http://ads.networksolutions.com/landing?code=P61C100S1N0B142A1D255E0000V100">Web Hosting</a> powered by Network Solutions&reg;</p></td>
</tr>
</table>
<!-- End content section --><!-- Start Superstats code version 3.0b.  Copyright 1997-2001 MyComputer.com, Inc. More info available at http://www.mycomputer.com --><script language="JavaScript">/* You may give each page an identifying name, server, and channel on the next lines. */var pageName = "test";/**** DO NOT ALTER ANYTHING BELOW THIS LINE! ****/var code = ' '; </script><script src="http://code.superstats.com/code/ss/vsign_4515656/0/30b"></script><script language="JavaScript">br = navigator.appName + parseInt(navigator.appVersion);if (code != ' ' || br == 'Netscape2') document.write(code);else document.write(''+ ' <im'+'g'+ ' src="http://stats.superstats.com/b/ss/vsign_4515656/1'+ '?pageName=' +escape(pageName) + '" border=0>');</script><noscript><img src="http://stats.superstats.com/b/ss/vsign_4515656/1"border=0></noscript><!--End Superstats tracking code. --></body></html>