<?
$firstname = $_POST['firstname'];
$lastname = $_POST['lastname'];
$address_line_1 = $_POST['add_line_1'];
$address_line_2 = $_POST['add_line_2'];
$address_city = $_POST['city'];
$address_state = $POST['state'];
$address_zipcode = $_POST['zipcode'];
$address_country = $_POST['country'];
$emailid = $_POST['emailid'];
$phonenum = $_POST['phonenum'];
$amount_to_donate = $_POST['amount_to_donate'];
$project_to_donate = $_POST['project_to_donate'];
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Confirm details -- Donation form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Confirm details - Donation</a></h1>
		<form id="form_87639" class="appnitro"  method="post" action="gatewayredirect.php">
					<div class="form_description">
			<h2>Confirm details - Donation</h2>
			<p>Please confirm the details below before making the donation. The information below will be used while generating the project certificates.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Name* </label>
		<span>
			<p><? echo "$firstname $lastname"?></p>
		</span>
		</li>
		
		<li id="li_2" >
		<label class="description" for="element_2">Address* </label>
		<span>
			<p><? echo "$address_line_1" ?></p>
			<p><? echo "$address_line_2" ?></p>
			<p><? echo "$address_city" ?></p>
			<p><? echo "$address_state" ?></p>
			<p><? echo "$address_zipcode" ?></p>
			<p><? echo "$address_country" ?></p>
		</span>
		
		<li id="li_3" >
		<label class="description" for="element_3">Email* </label>
		<span>
			<p><? echo "$emailid"?></p>
		</span>

		</li>

		<li id="li_6" >
		<label class="description" for="element_6">Your phone number</label>
		<span>
			<p><? echo "$phonenum"?></p>
		</span>

		<li id="li_5" >
		<label class="description" for="element_5">Amount that you are donating (in Indian Rupees)</label>
		<span>
			<p><? echo "$amount_to_donate"?></p>
		</span>
	 
		</li>		<li id="li_7" >
		<label class="description" for="element_7">Project to which you are making donation </label>
		<span>
			<p><? echo "$project_to_donate"?></p>
		</span>

<li class="buttons">
    <input type="hidden" name="form_id" value="87639" />
    <input id="saveForm" class="button_text" type="submit" name="submit" value="Donate" />
</li>
</ul>
	</form>	

<div id="footer">Generated by <a href="http://www.phpform.org">pForm</a></div>

</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>